postgresql:
  image: sameersbn/postgresql:9.4-11
  environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
redmine:
  image: sameersbn/redmine:3.2.0-1
  links:
    - postgresql:postgresql
  environment:
    - REDMINE_PORT=10083
    - REDMINE_RELATIVE_URL_ROOT=/redmine
  ports:
    - "127.0.0.1:10083:80"
